global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Network Automation MCP Server
  - job_name: 'network-automation'
    static_configs:
      - targets: ['network-automation:8000']
    scrape_interval: 15s
    metrics_path: /metrics
    
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Add network device monitoring (if SNMP exporter is available)
  # - job_name: 'network-devices'
  #   static_configs:
  #     - targets: ['192.168.100.10:161', '192.168.100.11:161']  # SPINE routers
  #     - targets: ['192.168.100.12:161', '192.168.100.13:161', '192.168.100.14:161', '192.168.100.15:161']  # LEAF switches
  #   params:
  #     module: [if_mib]
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: __param_target
  #     - source_labels: [__param_target]
  #       target_label: instance
  #     - target_label: __address__
  #       replacement: snmp-exporter:9116

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
