# Production Environment Configuration
# Production-specific settings and security configurations

# API Configuration (Production)
api:
  debug: false
  workers: 8  # More workers for production
  timeout: 60
  rate_limiting:
    requests_per_minute: 100
    burst_limit: 50

# MCP Server Configuration
mcp:
  log_level: "INFO"
  max_connections: 100

# Monitoring Configuration (Production)
monitoring:
  logging:
    level: "INFO"
    file_output: true
    log_rotation: true
    max_file_size: "100MB"
    backup_count: 10
  health_checks:
    timeout: 5
    detailed_status: false
  alerting:
    enabled: true
    slack_webhook: "${slack_webhook_url}"
    email_notifications: true

# Database Configuration (Production)
database:
  type: "postgresql"
  host: "${db_host}"
  port: 5432
  database: "${db_name}"
  username: "${db_username}"
  password: "${db_password}"
  ssl_mode: "require"
  pool_size: 20
  max_overflow: 30
  echo_sql: false

# Network Configuration (Production)
network:
  device_timeout: 60
  connection_retry: 5
  concurrent_connections: 20
  connection_pooling: true
  ssl_verification: true

# Security Configuration (Production)
security:
  encryption:
    enabled: true
    key_rotation: true
    key_rotation_interval: 86400  # 24 hours
  authentication:
    enabled: true
    method: "oauth2"
    token_expiry: 1800  # 30 minutes
    refresh_token_expiry: 604800  # 7 days
  authorization:
    enabled: true
    rbac: true
    audit_logging: true
  tls:
    enabled: true
    cert_path: "/etc/ssl/certs/app.crt"
    key_path: "/etc/ssl/private/app.key"

# Backup Configuration (Production)
backup:
  enabled: true
  retention_days: 90
  storage_type: "s3"
  s3_bucket: "${backup_s3_bucket}"
  encryption: true
  compression: true

# Cache Configuration (Production)
cache:
  enabled: true
  type: "redis"
  host: "${redis_host}"
  port: 6379
  password: "${redis_password}"
  ttl: 3600
  max_connections: 50

# Deployment Configuration (Production)
deployment:
  max_replicas: 5
  min_replicas: 2
  auto_scaling:
    enabled: true
    cpu_threshold: 70
    memory_threshold: 80
  rolling_update:
    max_surge: 1
    max_unavailable: 0

# External Services (Production)
external_services:
  timeout: 30
  retry_count: 3
  circuit_breaker:
    enabled: true
    failure_threshold: 5
    timeout: 30

# Resource Limits
resources:
  memory_limit: "2Gi"
  cpu_limit: "1000m"
  memory_request: "1Gi"
  cpu_request: "500m"

# Observability (Production)
observability:
  tracing:
    enabled: true
    sampling_rate: 0.1
    jaeger_endpoint: "${jaeger_endpoint}"
  metrics:
    enabled: true
    prometheus_pushgateway: "${prometheus_pushgateway_url}"
  profiling:
    enabled: false  # Disable profiling in production
